## Filament Activity Log Plus (asignua/filament-activity-log-plus)

- An audit trail on top of `spatie/laravel-activitylog` 5. Put a model under audit with `use Asignua\FilamentActivityLogPlus\Concerns\LogsActivityPlus;` (it already includes spatie's `LogsActivity`; do not add both). It uses `logAll()`, so `$guarded = ['*']` models are logged too.
- Optional model hooks (all `protected`): `activityExcept(): array` (own secrets; never override `activityExceptAll()`), `activityTranslatableAttributes(): array` (JSON `{locale: value}` columns; automatic with spatie/laravel-translatable), `activityIgnoreOnlyChanged(): array` (derived columns such as a materialised path).
- Pivots fire no Eloquent events. Use `use LogsPivotSync;` and `$post->syncAndLog('tags', $ids)`, or dispatch `PivotSynced::dispatch($owner, 'tags', attached: [...], detached: [...], titles: [id => title])`. A raw `->sync()` is invisible to the log. Titles are stored at the moment of the action; replace the resolver with `PivotTitles::using(fn (string $relation, array $ids, Model $owner): array => [...])`.
- Console and queue code has no request, so wrap multi-write operations in `app(ActivityBatch::class)->run(fn () => ...)`: one batch_uuid, one root. Panel requests are batched by the plugin's middleware and a Livewire `request` hook.
- Silence derived state with `activity()->withoutLogging(fn () => ...)`; otherwise a cascading save writes a row per descendant.
- Custom events: write with `activity()->performedOn($owner)->event('approved')->withProperties([...])->log('approved')`, always against the OWNER, and register the presentation with `ActivityEvents::register('approved', 'Approved', color: 'success', summary: fn (Activity $a): string => ..., view: 'my::partial')`. Unregistered events show their raw name.
- Labels: `FieldLabels::register([...])` or the `field_labels` config (key = COLUMN; `title` covers `title.uk`); `SubjectLabels::using(fn (Model $m): ?string => ...)` for record labels; the `subjects` config for type labels. Labels are stored at the moment of the action, in the current locale.
- Media: spatie/laravel-medialibrary is wired automatically. Other libraries: `MediaAdapters::register(Model::class, owner: fn ($m) => ..., properties: fn ($m) => [...], events: ['created' => 'media_attached', 'deleted' => 'media_detached'])`.
- Panel: `->plugin(ActivityLogPlusPlugin::make()->authorizeResource(fn () => ...)->authorizeHistory(fn () => ...)->navigationGroup('System'))`; add `ActivityHistoryAction::make()` as an explicit header action on each Edit/View page. The resource is read-only and CLOSED by default: without `authorizeResource()` or the `activity-log-plus.view` gate nobody sees it.
- Tables: publish BOTH stubs only as needed: `vendor:publish --tag=filament-activity-log-plus-migrations` gives `create_activity_log_plus_table` (new install) and `add_activity_log_plus_columns` (an existing spatie table); run one of them. The table name is the `activity-log-plus.table` config.
- The plugin sets `activitylog.activity_model` and `activitylog.actions.log_activity` only while they are still spatie's defaults. A host model must extend `Asignua\FilamentActivityLogPlus\Models\Activity`, a host action must extend `Asignua\FilamentActivityLogPlus\Actions\LogActivityAction`.
- Never use the stock `collection`/`array` cast for log columns: `Casts\UnescapedJsonCollection` keeps non-ASCII text readable in the database.
- Prune: `activity-log-plus:prune {--days=}` (config `retention_days`, 0 = off); `schedule.enabled` runs it daily.
